set -e
set -x

# ===========================================================
# Train Qwen3-1.7B student via Agent Distillation
#
# Usage:
#   bash scripts/training/train_agent_qwen3.sh [TEACHER] [STUDENT_MODEL] [EPOCH]
#
#   TEACHER options:
#     qwen25  (default) — use Qwen2.5-32B trajectories from HuggingFace Hub
#     qwen3            — use Qwen3-32B trajectories generated locally
#                        (run scripts/inference/run_agent_teacher_train_qwen3.sh first)
# ===========================================================

TEACHER=${1:-"qwen3"}
MODEL=${2:-"Qwen/Qwen3-1.7B"}
EPOCH=${3:-2}

if [ "$TEACHER" = "qwen3" ]; then
  # ---- Qwen3-32B teacher: local filtered trajectories --------------------
  SAVENAME="qwen3_32B_teacher"

  # Paths to filtered trajectory files generated by run_agent_teacher_train_qwen3.sh
  DATASETS=(
    "logs/qa_results/vllm/Qwen_Qwen3-32B/hotpotqa_1000_20250402_train/filtered_data/Qwen3-32B_temp=0.0_seed=42_type=agent_filtered.jsonl"
    "logs/qa_results/vllm/Qwen_Qwen3-32B/math_1000_20250414_train/filtered_data/Qwen3-32B_temp=0.0_seed=42_type=agent_filtered.jsonl"
    "logs/qa_results/vllm/Qwen_Qwen3-32B/math_medium_1000_20250430_train/filtered_data/Qwen3-32B_temp=0.0_seed=42_type=agent_filtered.jsonl"
  )

  # Verify files exist before starting training
  for f in "${DATASETS[@]}"; do
    if [ ! -f "$f" ]; then
      echo "❌ Trajectory file not found: $f"
      echo "   Run scripts/inference/run_agent_teacher_train_qwen3.sh first."
      exit 1
    fi
  done
  echo "✅ All Qwen3-32B trajectory files found."

else
  # ---- Qwen2.5-32B teacher: HuggingFace Hub dataset (default) -----------
  SAVENAME="qwen2.5_32B_teacher"
  DATASETS=(
    "agent-distillation/Qwen2.5-32B-Instruct_agent_trajectories_2k"
  )
fi

JOINED_DATASETS=$(IFS=" "; echo "${DATASETS[*]}")

echo "Teacher : $TEACHER"
echo "Student : $MODEL"
echo "Epochs  : $EPOCH"
echo "Dataset : $JOINED_DATASETS"

sh exps_research/scripts_train/finetune_sft_agent.sh \
    "$MODEL" \
    "$JOINED_DATASETS" \
    "$SAVENAME" \
    "$EPOCH"
